import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from './context/ThemeContex';
import ThemeInitializer from './web_components/ThemeInitializer';
import ClientLayout from './ClientLayout';
import { FrontUI } from './context/FrontPageUiContext';
import { Front2UI } from './context/FrontPage2Context';
// import BlogCardImg from './page_components/BlogCardImg';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider>
          <ThemeInitializer />
          <ClientLayout>
          
          <FrontUI>
            <Front2UI>
                 {children}
            </Front2UI>
            </FrontUI>
            {/* <BlogCardImg /> */}
   
          </ClientLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
